export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS'
export const SELECT_CURRENT_PROJECT = 'SELECT_CURRENT_PROJECT'
